# Generated by Django 5.1.5 on 2025-02-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_cover_img_book_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
